import { BaseStyles, ThemeProvider } from "@primer/react";
import type { Metadata } from "next";
import StyledComponentsRegistry from "../lib/registry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <link
          rel="stylesheet"
          href="https://unpkg.com/@primer/css/dist/primer.css"
        ></link>
        <ThemeProvider>
          <StyledComponentsRegistry>
            <BaseStyles>{children}</BaseStyles>
          </StyledComponentsRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
